import * as XLSX from 'xlsx';

const SHEET_NAMES = {
    INSTRUCTIONS: 'Instructions',
    CASH: 'Cash',
    INVESTMENTS: 'Investments',
    ORDERS: 'Orders',
    LIABILITIES: 'Liabilities',
    CREDIT_CARDS: 'CreditCards',
    CASHFLOW: 'CashFlow',
    SETTINGS: 'Settings',
};

const REQUIRED_SHEETS = Object.values(SHEET_NAMES).filter(s => s !== SHEET_NAMES.INSTRUCTIONS);

function toNum(val) {
    if (val === null || val === undefined || val === '') return null;
    const n = Number(val);
    return isNaN(n) ? null : n;
}

function toBool(val) {
    if (typeof val === 'boolean') return val;
    if (typeof val === 'string') return val.trim().toUpperCase() === 'TRUE';
    return Boolean(val);
}

function toDateStr(val) {
    if (!val) return null;
    if (typeof val === 'number') {
        const date = XLSX.SSF.parse_date_code(val);
        if (!date) return null;
        const m = String(date.m).padStart(2, '0');
        const d = String(date.d).padStart(2, '0');
        return `${date.y}-${m}-${d}`;
    }
    if (typeof val === 'string' && val.trim()) {
        const s = val.trim();
        // Try to parse various date formats
        // YYYY-MM-DD, YYYY/MM/DD
        if (/^\d{4}[-/]\d{1,2}[-/]\d{1,2}$/.test(s)) {
            const parts = s.split(/[-/]/);
            const y = parts[0];
            const m = String(parts[1]).padStart(2, '0');
            const d = String(parts[2]).padStart(2, '0');
            return `${y}-${m}-${d}`;
        }
        // MM/DD/YYYY, DD/MM/YYYY (try both interpretations)
        if (/^\d{1,2}[-/]\d{1,2}[-/]\d{4}$/.test(s)) {
            const parts = s.split(/[-/]/);
            // Assume MM/DD/YYYY format (common in Excel)
            const m = String(parts[0]).padStart(2, '0');
            const d = String(parts[1]).padStart(2, '0');
            const y = parts[2];
            return `${y}-${m}-${d}`;
        }
        return s;
    }
    return null;
}

function strip(item, keepId = false) {
    const { id, portfolio_id: _pid, created_at: _ca, updated_at: _ua, ...rest } = item;
    return keepId ? { id, ...rest } : rest;
}

function buildInstructionsData(isTemplate = false) {
    const lines = [
        ['Finance Tracker — Excel Backup'],
        [],
        ['HOW TO USE THIS FILE'],
        [],
        ['• Edit existing rows or add new rows to import data.'],
        ['• DO NOT rename sheets or change column headers.'],
        ['• Remove rows you do NOT want to import before uploading.'],
        ['• Importing adds data — it does not delete your existing records.'],
        [],
        ['DATE FORMAT IMPORTANT'],
        ['• Always enter dates in YYYY-MM-DD format (e.g., 2024-12-31).'],
        ['• Do NOT use Excel\'s default date format (DD/MM/YYYY or MM/DD/YYYY).'],
        ['• To format a cell as text: Right-click -> Format Cells -> Text -> type YYYY-MM-DD.'],
        [],
        ['SHEET GUIDE'],
        ['Cash', '→ Savings accounts and Fixed Deposits (table_type: Savings | FixedDeposit)'],
        ['Investments', '→ Mutual Funds, Stocks, and Crypto (asset_type: MutualFund | Stock | Crypto)'],
        ['Orders', '→ Buy/Sell order history (asset_type: MutualFund | Stock | Crypto)'],
        ['Liabilities', '→ Loans and other outstanding liabilities'],
        ['CreditCards', '→ Credit card details'],
        ['CashFlow', '→ Transactions and Budget limits (table_type: Transaction | Budget)'],
        ['Settings', '→ Portfolio settings (single row)'],
        [],
        ['FIELD GUIDE'],
        ['Investments → id', 'Leave BLANK for new entries. Auto-generated by system. Only fill if importing existing data.'],
        ['Investments → symbol (MF)', 'AMFI scheme code (e.g., 122639 for Parag Parikh Flexi Cap). Look up on AMFI India.'],
        ['Orders → Fund/Stock/Coin Name', 'Name of the holding (e.g., Parag Parikh Flexi Cap, RELIANCE, Bitcoin). Used to match with existing investments.'],
        ['Orders → holding_id', 'Optional: Leave BLANK to auto-match by name. Only fill if linking to specific existing investment by ID.'],
        ['Orders → amount_overridden', 'TRUE if you manually edited the amount (not units × price). FALSE otherwise.'],
        [],
        ['DATE FORMATS'],
        ['Accepted formats', 'YYYY-MM-DD (2025-12-04), MM/DD/YYYY (04/12/2025), or DD/MM/YYYY (04/12/2025)'],
        ['Excel behavior', 'Dates are automatically converted to YYYY-MM-DD format during import'],
        [],
        ['PRICE vs AMOUNT'],
        ['Price', 'Unit price (NAV for MF, price per share for stocks, price per coin for crypto).'],
        ['Amount', 'Total transaction value (units × price + charges). Can be manually overridden.'],
        [],
        ['VALID VALUES'],
        ['Orders → order_type', 'Buy | Sell'],
        ['CashFlow → type (Transaction rows only)', 'income | expense'],
        [],
        ['IMPORTING'],
        ['1.', 'Go to Settings → Import Data in the app'],
        ['2.', 'Select this .xlsx file'],
        ['3.', 'Data will be added to your portfolio'],
    ];

    if (isTemplate) {
        lines.splice(8, 0, ['• This is a TEMPLATE with sample rows. Replace sample data with your own.']);
        lines.push([]);
        lines.push(['SAMPLE DATA']);
        lines.push(['• Each sheet has one sample row per type for reference.']);
        lines.push(['• Delete sample rows after you understand the structure.']);
    }

    return lines;
}

function buildCashRows(savings, fixedDeposits) {
    const rows = [];
    for (const s of savings) {
        const r = strip(s);
        rows.push({ table_type: 'Savings', bank_name: r.bank_name || '', account_type: r.account_type || '', balance: toNum(r.balance), interest_rate: toNum(r.interest_rate), invested: '', maturity: '', maturity_date: '' });
    }
    for (const fd of fixedDeposits) {
        const r = strip(fd);
        rows.push({ table_type: 'FixedDeposit', bank_name: r.bank_name || '', account_type: '', balance: '', interest_rate: toNum(r.interest_rate), invested: toNum(r.invested), maturity: toNum(r.maturity), maturity_date: r.maturity_date || '' });
    }
    return rows;
}

function buildInvestmentsRows(mutualFunds, stocks, crypto, isTemplate = false) {
    const rows = [];
    for (const mf of mutualFunds) {
        const r = strip(mf, true);
        rows.push({ asset_type: 'MutualFund', id: isTemplate ? '' : (r.id || ''), name: r.fund_name || '', symbol: r.scheme_code || '', quantity: toNum(r.units), invested: toNum(r.invested), current: toNum(r.current), current_price: toNum(r.current_price), category: r.fund_type || '', sip: toNum(r.sip) });
    }
    for (const st of stocks) {
        const r = strip(st, true);
        rows.push({ asset_type: 'Stock', id: isTemplate ? '' : (r.id || ''), name: r.stock_name || '', symbol: r.ticker || '', quantity: toNum(r.quantity), invested: toNum(r.invested), current: toNum(r.current), current_price: toNum(r.current_price), category: r.sector || '', sip: '' });
    }
    for (const cr of crypto) {
        const r = strip(cr, true);
        rows.push({ asset_type: 'Crypto', id: isTemplate ? '' : (r.id || ''), name: r.coin_name || '', symbol: '', quantity: toNum(r.quantity), invested: toNum(r.invested), current: toNum(r.current), current_price: toNum(r.current_price), category: r.platform || '', sip: '' });
    }
    return rows;
}

function buildOrdersRows(mfOrders, stockOrders, cryptoOrders, holdings = { mutualFunds: [], stocks: [], crypto: [] }) {
    const rows = [];
    for (const o of mfOrders) {
        const r = strip(o);
        const mf = holdings.mutualFunds?.find(m => m.id === r.mf_id) || {};
        rows.push({ asset_type: 'MutualFund', name: mf.fund_name || '', holding_id: r.mf_id || '', execution_date: r.execution_date || '', order_type: r.order_type || '', units: toNum(r.units), nav: toNum(r.nav), quantity: '', price: '', amount: toNum(r.amount), charges: toNum(r.charges), platform: r.platform || '', remarks: r.remarks || '', amount_overridden: r.amount_overridden ? 'TRUE' : 'FALSE' });
    }
    for (const o of stockOrders) {
        const r = strip(o);
        const st = holdings.stocks?.find(s => s.id === r.stock_id) || {};
        rows.push({ asset_type: 'Stock', name: st.stock_name || '', holding_id: r.stock_id || '', execution_date: r.execution_date || '', order_type: r.order_type || '', units: '', nav: '', quantity: toNum(r.quantity), price: toNum(r.price), amount: toNum(r.amount), charges: toNum(r.charges), platform: r.platform || '', remarks: r.remarks || '', amount_overridden: r.amount_overridden ? 'TRUE' : 'FALSE' });
    }
    for (const o of cryptoOrders) {
        const r = strip(o);
        const cr = holdings.crypto?.find(c => c.id === r.crypto_id) || {};
        rows.push({ asset_type: 'Crypto', name: cr.coin_name || '', holding_id: r.crypto_id || '', execution_date: r.execution_date || '', order_type: r.order_type || '', units: '', nav: '', quantity: toNum(r.quantity), price: toNum(r.price), amount: toNum(r.amount), charges: toNum(r.charges), platform: r.platform || '', remarks: r.remarks || '', amount_overridden: r.amount_overridden ? 'TRUE' : 'FALSE' });
    }
    return rows;
}

function buildLiabilitiesRows(liabilities) {
    return liabilities.map(l => {
        const r = strip(l);
        return { type: r.type || '', lender: r.lender || '', loan_amount: toNum(r.loan_amount), outstanding: toNum(r.outstanding), interest_rate: toNum(r.interest_rate), emi: toNum(r.emi) };
    });
}

function buildCreditCardsRows(creditCards) {
    return creditCards.map(c => {
        const r = strip(c);
        return { card_name: r.card_name || '', bank_name: r.bank_name || '', last4: r.last4 || '', credit_limit: toNum(r.credit_limit), current_balance: toNum(r.current_balance), statement_balance: toNum(r.statement_balance), due_date: r.due_date || '', billing_date: r.billing_date || '' };
    });
}

function buildCashFlowRows(transactions, budgets) {
    const rows = [];
    for (const t of transactions) {
        const r = strip(t);
        rows.push({ table_type: 'Transaction', date: r.date || '', type: r.type || '', category: r.category || '', amount: toNum(r.amount), description: r.description || '', monthly_limit: '', notes: '' });
    }
    for (const b of budgets) {
        const r = strip(b);
        rows.push({ table_type: 'Budget', date: '', type: '', category: r.category || '', amount: '', description: '', monthly_limit: toNum(r.monthly_limit), notes: r.notes || '' });
    }
    return rows;
}

function buildSettingsRows(settings) {
    return settings.map(s => {
        const r = strip(s);
        return {
            currency: r.currency || 'INR',
            display_currency: r.display_currency || 'INR',
            goal: toNum(r.goal),
            epf: toNum(r.epf),
            ppf: toNum(r.ppf),
            username: r.username || '',
            gender: r.gender || '',
            profession: r.profession || '',
            date_of_birth: r.date_of_birth || '',
            location: r.location || '',
            marital_status: r.marital_status || '',
            dependents: r.dependents || 0,
            risk_tolerance: r.risk_tolerance || '',
        };
    });
}

function getSheetRows(wb, sheetName) {
    const ws = wb.Sheets[sheetName];
    if (!ws) throw new Error(`Missing required sheet: "${sheetName}"`);
    return XLSX.utils.sheet_to_json(ws, { defval: '' });
}

function parseCashRows(rows) {
    const savings = [];
    const fixedDeposits = [];
    for (const row of rows) {
        const t = String(row.table_type || '').trim();
        if (t === 'Savings') {
            savings.push({ bank_name: row.bank_name, account_type: row.account_type, balance: toNum(row.balance), interest_rate: toNum(row.interest_rate) });
        } else if (t === 'FixedDeposit') {
            fixedDeposits.push({ bank_name: row.bank_name, invested: toNum(row.invested), maturity: toNum(row.maturity), interest_rate: toNum(row.interest_rate), maturity_date: toDateStr(row.maturity_date) });
        } else if (t) {
            throw new Error(`Cash sheet: unknown table_type "${t}". Expected "Savings" or "FixedDeposit".`);
        }
    }
    return { savings, fixedDeposits };
}

function parseInvestmentsRows(rows) {
    const mutualFunds = [];
    const stocks = [];
    const crypto = [];
    for (const row of rows) {
        const t = String(row.asset_type || '').trim();
        const id = row.id ? String(row.id).trim() : undefined;
        if (t === 'MutualFund') {
            const obj = { fund_name: row.name, scheme_code: row.symbol, units: toNum(row.quantity), invested: toNum(row.invested), current: toNum(row.current), current_price: toNum(row.current_price), fund_type: row.category, sip: toNum(row.sip) };
            if (id) obj.id = id;
            mutualFunds.push(obj);
        } else if (t === 'Stock') {
            const obj = { stock_name: row.name, ticker: row.symbol, quantity: toNum(row.quantity), invested: toNum(row.invested), current: toNum(row.current), current_price: toNum(row.current_price), sector: row.category };
            if (id) obj.id = id;
            stocks.push(obj);
        } else if (t === 'Crypto') {
            const obj = { coin_name: row.name, quantity: toNum(row.quantity), invested: toNum(row.invested), current: toNum(row.current), current_price: toNum(row.current_price), platform: row.category };
            if (id) obj.id = id;
            crypto.push(obj);
        } else if (t) {
            throw new Error(`Investments sheet: unknown asset_type "${t}". Expected "MutualFund", "Stock", or "Crypto".`);
        }
    }
    return { mutualFunds, stocks, crypto };
}

function parseOrdersRows(rows, holdings = { mutualFunds: [], stocks: [], crypto: [] }) {
    const mfOrders = [];
    const stockOrders = [];
    const cryptoOrders = [];
    for (const row of rows) {
        const t = String(row.asset_type || '').trim();
        const name = String(row.name || '').trim();
        const holdingId = String(row.holding_id || '').trim();
        const base = { execution_date: toDateStr(row.execution_date) || row.execution_date, order_type: row.order_type, amount: toNum(row.amount), charges: toNum(row.charges) ?? 0, platform: row.platform || '', remarks: row.remarks || '', amount_overridden: toBool(row.amount_overridden) };

        if (t === 'MutualFund') {
            let mfId = holdingId;
            if (!mfId && name) {
                const matched = holdings.mutualFunds?.find(m => m.fund_name?.toLowerCase() === name.toLowerCase());
                if (matched) mfId = matched.id;
            }
            mfOrders.push({ ...base, mf_id: mfId, units: toNum(row.units), nav: toNum(row.nav) });
        } else if (t === 'Stock') {
            let stockId = holdingId;
            if (!stockId && name) {
                const matched = holdings.stocks?.find(s => s.stock_name?.toLowerCase() === name.toLowerCase());
                if (matched) stockId = matched.id;
            }
            stockOrders.push({ ...base, stock_id: stockId, quantity: toNum(row.quantity), price: toNum(row.price) });
        } else if (t === 'Crypto') {
            let cryptoId = holdingId;
            if (!cryptoId && name) {
                const matched = holdings.crypto?.find(c => c.coin_name?.toLowerCase() === name.toLowerCase());
                if (matched) cryptoId = matched.id;
            }
            cryptoOrders.push({ ...base, crypto_id: cryptoId, quantity: toNum(row.quantity), price: toNum(row.price) });
        } else if (t) {
            throw new Error(`Orders sheet: unknown asset_type "${t}". Expected "MutualFund", "Stock", or "Crypto".`);
        }
    }
    return { mfOrders, stockOrders, cryptoOrders };
}

function parseLiabilitiesRows(rows) {
    return rows.filter(r => String(r.type || '').trim()).map(r => ({ type: r.type, lender: r.lender, loan_amount: toNum(r.loan_amount), outstanding: toNum(r.outstanding), interest_rate: toNum(r.interest_rate), emi: toNum(r.emi) }));
}

function parseCreditCardsRows(rows) {
    return rows.filter(r => String(r.card_name || '').trim()).map(r => ({ card_name: r.card_name, bank_name: r.bank_name, last4: r.last4, credit_limit: toNum(r.credit_limit), current_balance: toNum(r.current_balance), statement_balance: toNum(r.statement_balance), due_date: r.due_date || '', billing_date: r.billing_date || '' }));
}

function parseCashFlowRows(rows) {
    const transactions = [];
    const budgets = [];
    for (const row of rows) {
        const t = String(row.table_type || '').trim();
        if (t === 'Transaction') {
            transactions.push({ date: toDateStr(row.date) || row.date, type: row.type, category: row.category, amount: toNum(row.amount), description: row.description || '' });
        } else if (t === 'Budget') {
            budgets.push({ category: row.category, monthly_limit: toNum(row.monthly_limit), notes: row.notes || '' });
        } else if (t) {
            throw new Error(`CashFlow sheet: unknown table_type "${t}". Expected "Transaction" or "Budget".`);
        }
    }
    return { transactions, budgets };
}

function parseSettingsRows(rows) {
    return rows.filter(r => r.currency).map(r => ({
        currency: r.currency,
        display_currency: r.display_currency || r.currency,
        goal: toNum(r.goal),
        epf: toNum(r.epf),
        ppf: toNum(r.ppf),
        username: r.username || '',
        gender: r.gender || null,
        profession: r.profession || null,
        date_of_birth: r.date_of_birth || null,
        location: r.location || null,
        marital_status: r.marital_status || null,
        dependents: toNum(r.dependents) || 0,
        risk_tolerance: r.risk_tolerance || null,
    }));
}

function buildSheetWithHeaders(rows, headerRow) {
    if (rows.length > 0) return XLSX.utils.json_to_sheet(rows);
    return XLSX.utils.aoa_to_sheet([headerRow]);
}

export const DataUtils = {
    parseOrdersRows,
    exportToExcel(data, filename = 'finance-backup.xlsx') {
        const wb = XLSX.utils.book_new();

        const instrWs = XLSX.utils.aoa_to_sheet(buildInstructionsData(false));
        XLSX.utils.book_append_sheet(wb, instrWs, SHEET_NAMES.INSTRUCTIONS);

        const cashRows = buildCashRows(data.savings || [], data.fixedDeposits || []);
        XLSX.utils.book_append_sheet(wb, buildSheetWithHeaders(cashRows, ['table_type', 'bank_name', 'account_type', 'balance', 'interest_rate', 'invested', 'maturity', 'maturity_date']), SHEET_NAMES.CASH);

        const invRows = buildInvestmentsRows(data.mutualFunds || [], data.stocks || [], data.crypto || [], false);
        XLSX.utils.book_append_sheet(wb, buildSheetWithHeaders(invRows, ['asset_type', 'id', 'name', 'symbol', 'quantity', 'invested', 'current', 'current_price', 'category', 'sip']), SHEET_NAMES.INVESTMENTS);

        const ordRows = buildOrdersRows(data.mfOrders || [], data.stockOrders || [], data.cryptoOrders || [], { mutualFunds: data.mutualFunds || [], stocks: data.stocks || [], crypto: data.crypto || [] });
        XLSX.utils.book_append_sheet(wb, buildSheetWithHeaders(ordRows, ['asset_type', 'name', 'holding_id', 'execution_date', 'order_type', 'units', 'nav', 'quantity', 'price', 'amount', 'charges', 'platform', 'remarks', 'amount_overridden']), SHEET_NAMES.ORDERS);

        const liabRows = buildLiabilitiesRows(data.liabilities || []);
        XLSX.utils.book_append_sheet(wb, buildSheetWithHeaders(liabRows, ['type', 'lender', 'loan_amount', 'outstanding', 'interest_rate', 'emi']), SHEET_NAMES.LIABILITIES);

        const ccRows = buildCreditCardsRows(data.creditCards || []);
        XLSX.utils.book_append_sheet(wb, buildSheetWithHeaders(ccRows, ['card_name', 'bank_name', 'last4', 'credit_limit', 'current_balance', 'statement_balance', 'due_date', 'billing_date']), SHEET_NAMES.CREDIT_CARDS);

        const cfRows = buildCashFlowRows(data.transactions || [], data.budgets || []);
        XLSX.utils.book_append_sheet(wb, buildSheetWithHeaders(cfRows, ['table_type', 'date', 'type', 'category', 'amount', 'description', 'monthly_limit', 'notes']), SHEET_NAMES.CASHFLOW);

        const settRows = buildSettingsRows(data.settings || []);
        XLSX.utils.book_append_sheet(wb, buildSheetWithHeaders(settRows, ['currency', 'display_currency', 'goal', 'epf', 'ppf', 'username', 'gender', 'profession', 'date_of_birth', 'location', 'marital_status', 'dependents', 'risk_tolerance']), SHEET_NAMES.SETTINGS);

        XLSX.writeFile(wb, filename);
    },

    createTemplate(filename = 'finance-tracker-template.xlsx') {
        const wb = XLSX.utils.book_new();

        const instrWs = XLSX.utils.aoa_to_sheet(buildInstructionsData(true));
        XLSX.utils.book_append_sheet(wb, instrWs, SHEET_NAMES.INSTRUCTIONS);

        const templateCashRows = [
            { table_type: 'Savings', bank_name: 'HDFC Bank', account_type: 'Salary', balance: 50000, interest_rate: 3.5, invested: '', maturity: '', maturity_date: '' },
            { table_type: 'FixedDeposit', bank_name: 'SBI', account_type: '', balance: '', interest_rate: 7.5, invested: 100000, maturity: 115000, maturity_date: '2025-12-31' },
        ];
        XLSX.utils.book_append_sheet(wb, XLSX.utils.json_to_sheet(templateCashRows), SHEET_NAMES.CASH);

        const templateInvRows = [
            { asset_type: 'MutualFund', id: '', name: 'Parag Parikh Flexi Cap Fund', symbol: '122639', quantity: 100, invested: 10000, current: 12000, current_price: 120, category: 'Equity', sip: 5000 },
            { asset_type: 'Stock', id: '', name: 'Reliance Industries', symbol: 'RELIANCE', quantity: 10, invested: 25000, current: 28000, current_price: 2800, category: 'Energy', sip: '' },
            { asset_type: 'Crypto', id: '', name: 'Bitcoin', symbol: 'BTC', quantity: 0.001, invested: 3000, current: 3500, current_price: 3500000, category: 'Binance', sip: '' },
        ];
        XLSX.utils.book_append_sheet(wb, XLSX.utils.json_to_sheet(templateInvRows), SHEET_NAMES.INVESTMENTS);

        const templateOrdRows = [
            { asset_type: 'MutualFund', name: 'Parag Parikh Flexi Cap Fund', holding_id: '', execution_date: '2024-01-10', order_type: 'Buy', units: 50, nav: 100, quantity: '', price: '', amount: 5000, charges: 0, platform: 'Zerodha', remarks: '', amount_overridden: 'FALSE' },
            { asset_type: 'Stock', name: 'Reliance Industries', holding_id: '', execution_date: '2024-01-12', order_type: 'Buy', units: '', nav: '', quantity: 5, price: 2500, amount: 12500, charges: 25, platform: 'Zerodha', remarks: '', amount_overridden: 'FALSE' },
            { asset_type: 'Crypto', name: 'Bitcoin', holding_id: '', execution_date: '2024-01-08', order_type: 'Buy', units: '', nav: '', quantity: 0.0005, price: 3000000, amount: 1500, charges: 10, platform: 'Binance', remarks: 'test', amount_overridden: 'TRUE' },
        ];
        XLSX.utils.book_append_sheet(wb, XLSX.utils.json_to_sheet(templateOrdRows), SHEET_NAMES.ORDERS);

        const templateLiabRows = [
            { type: 'Car Loan', lender: 'SBI', loan_amount: 500000, outstanding: 300000, interest_rate: 8.5, emi: 12000 },
        ];
        XLSX.utils.book_append_sheet(wb, XLSX.utils.json_to_sheet(templateLiabRows), SHEET_NAMES.LIABILITIES);

        const templateCcRows = [
            { card_name: 'HDFC Regalia', bank_name: 'HDFC', last4: '1234', credit_limit: 100000, current_balance: 5000, statement_balance: 4500, due_date: '2024-02-15', billing_date: '2024-02-05' },
        ];
        XLSX.utils.book_append_sheet(wb, XLSX.utils.json_to_sheet(templateCcRows), SHEET_NAMES.CREDIT_CARDS);

        const templateCfRows = [
            { table_type: 'Transaction', date: '2024-01-15', type: 'income', category: 'Salary', amount: 80000, description: 'January salary', monthly_limit: '', notes: '' },
            { table_type: 'Budget', date: '', type: '', category: 'Food', amount: '', description: '', monthly_limit: 10000, notes: '' },
        ];
        XLSX.utils.book_append_sheet(wb, XLSX.utils.json_to_sheet(templateCfRows), SHEET_NAMES.CASHFLOW);

        const templateSettRows = [
            { currency: 'INR', display_currency: 'INR', goal: 5000000, epf: 200000, ppf: 50000, username: 'John Doe', gender: 'male', profession: 'Software Engineer', date_of_birth: '1990-05-15', location: 'Bangalore, India', marital_status: 'married', dependents: 1, risk_tolerance: 'moderate' },
        ];
        XLSX.utils.book_append_sheet(wb, XLSX.utils.json_to_sheet(templateSettRows), SHEET_NAMES.SETTINGS);

        XLSX.writeFile(wb, filename);
    },

    importFromExcel(file) {
        return new Promise((resolve, reject) => {
            if (!file) { reject(new Error('No file provided')); return; }
            if (!file.name.endsWith('.xlsx')) { reject(new Error('Invalid file type. Please select an .xlsx file.')); return; }
            if (file.size > 10 * 1024 * 1024) { reject(new Error('File size too large. Maximum size is 10MB.')); return; }

            const reader = new FileReader();
            reader.onload = (e) => {
                try {
                    const wb = XLSX.read(e.target.result, { type: 'array', cellDates: false });

                    for (const name of REQUIRED_SHEETS) {
                        if (!wb.SheetNames.includes(name)) throw new Error(`Missing required sheet: "${name}"`);
                    }

                    const cashResult = parseCashRows(getSheetRows(wb, SHEET_NAMES.CASH));
                    const invResult = parseInvestmentsRows(getSheetRows(wb, SHEET_NAMES.INVESTMENTS));
                    const ordResult = parseOrdersRows(getSheetRows(wb, SHEET_NAMES.ORDERS), invResult);
                    const liabilities = parseLiabilitiesRows(getSheetRows(wb, SHEET_NAMES.LIABILITIES));
                    const creditCards = parseCreditCardsRows(getSheetRows(wb, SHEET_NAMES.CREDIT_CARDS));
                    const cfResult = parseCashFlowRows(getSheetRows(wb, SHEET_NAMES.CASHFLOW));
                    const settings = parseSettingsRows(getSheetRows(wb, SHEET_NAMES.SETTINGS));

                    resolve({
                        savings: cashResult.savings,
                        fixedDeposits: cashResult.fixedDeposits,
                        mutualFunds: invResult.mutualFunds,
                        stocks: invResult.stocks,
                        crypto: invResult.crypto,
                        liabilities,
                        creditCards,
                        transactions: cfResult.transactions,
                        budgets: cfResult.budgets,
                        settings,
                        mfOrders: ordResult.mfOrders,
                        stockOrders: ordResult.stockOrders,
                        cryptoOrders: ordResult.cryptoOrders,
                    });
                } catch (err) {
                    reject(new Error('Failed to parse Excel file: ' + err.message));
                }
            };
            reader.onerror = () => reject(new Error('Failed to read file'));
            reader.readAsArrayBuffer(file);
        });
    },
};
